"""PyBlueHost HCI layer — packet codec, flow control, vendor constants."""

from pybluehost.hci.constants import (
    OGF,
    EventCode,
    ErrorCode,
    LEMetaSubEvent,
    make_opcode,
    ogf_ocf,
    HCI_COMMAND_PACKET,
    HCI_ACL_PACKET,
    HCI_SCO_PACKET,
    HCI_EVENT_PACKET,
    HCI_ISO_PACKET,
    HCI_RESET,
    HCI_READ_BD_ADDR,
    HCI_READ_BUFFER_SIZE,
    HCI_READ_LOCAL_VERSION,
    HCI_LE_READ_BUFFER_SIZE,
    HCI_LE_SET_SCAN_ENABLE,
    HCI_DISCONNECT,
)
from pybluehost.hci.flow import ACLFlowController, CommandFlowController
from pybluehost.hci.packets import (
    HCIACLData,
    HCICommand,
    HCIEvent,
    HCIISOData,
    HCIPacket,
    HCISCOData,
    HCI_Command_Complete_Event,
    HCI_Command_Status_Event,
    HCI_Connection_Complete_Event,
    HCI_Disconnection_Complete_Event,
    HCI_LE_Meta_Event,
    HCI_LE_Set_Scan_Enable,
    HCI_Number_Of_Completed_Packets_Event,
    HCI_Reset,
    PacketRegistry,
    decode_hci_packet,
)

__all__ = [
    # Constants
    "OGF",
    "EventCode",
    "ErrorCode",
    "LEMetaSubEvent",
    "make_opcode",
    "ogf_ocf",
    "HCI_COMMAND_PACKET",
    "HCI_ACL_PACKET",
    "HCI_SCO_PACKET",
    "HCI_EVENT_PACKET",
    "HCI_ISO_PACKET",
    "HCI_RESET",
    "HCI_READ_BD_ADDR",
    "HCI_READ_BUFFER_SIZE",
    "HCI_READ_LOCAL_VERSION",
    "HCI_LE_READ_BUFFER_SIZE",
    "HCI_LE_SET_SCAN_ENABLE",
    "HCI_DISCONNECT",
    # Packets
    "HCIPacket",
    "HCICommand",
    "HCIEvent",
    "HCIACLData",
    "HCISCOData",
    "HCIISOData",
    "HCI_Reset",
    "HCI_LE_Set_Scan_Enable",
    "HCI_Command_Complete_Event",
    "HCI_Command_Status_Event",
    "HCI_Connection_Complete_Event",
    "HCI_Disconnection_Complete_Event",
    "HCI_Number_Of_Completed_Packets_Event",
    "HCI_LE_Meta_Event",
    "PacketRegistry",
    "decode_hci_packet",
    # Flow control
    "CommandFlowController",
    "ACLFlowController",
]
