"""PyBlueHost HCI layer — packet codec, flow control, vendor constants."""

from pybluehost.hci.constants import (
    OGF,
    EventCode,
    ErrorCode,
    LEMetaSubEvent,
    make_opcode,
    ogf_ocf,
    HCI_COMMAND_PACKET,
    HCI_ACL_PACKET,
    HCI_SCO_PACKET,
    HCI_EVENT_PACKET,
    HCI_ISO_PACKET,
    HCI_RESET,
    HCI_READ_BD_ADDR,
    HCI_READ_BUFFER_SIZE,
    HCI_READ_LOCAL_VERSION,
    HCI_LE_READ_BUFFER_SIZE,
    HCI_LE_SET_SCAN_ENABLE,
    HCI_DISCONNECT,
    HCI_SET_EVENT_MASK,
    HCI_LE_SET_EVENT_MASK,
    HCI_WRITE_LE_HOST_SUPPORTED,
    HCI_WRITE_SIMPLE_PAIRING_MODE,
    HCI_WRITE_SCAN_ENABLE,
    HCI_HOST_BUFFER_SIZE,
    HCI_LE_SET_SCAN_PARAMS,
    HCI_LE_SET_RANDOM_ADDRESS,
    HCI_READ_LOCAL_SUPPORTED_COMMANDS,
    HCI_READ_LOCAL_SUPPORTED_FEATURES,
    HCI_LE_READ_LOCAL_SUPPORTED_FEATURES,
)
from pybluehost.hci.controller import ConnectionManager, HCIConnection, HCIController
from pybluehost.hci.flow import ACLFlowController, CommandFlowController
from pybluehost.hci.virtual import VirtualController
from pybluehost.hci.packets import (
    HCIACLData,
    HCICommand,
    HCIEvent,
    HCIISOData,
    HCIPacket,
    HCISCOData,
    HCI_Command_Complete_Event,
    HCI_Command_Status_Event,
    HCI_Connection_Complete_Event,
    HCI_Disconnection_Complete_Event,
    HCI_Host_Buffer_Size_Command,
    HCI_LE_Meta_Event,
    HCI_LE_Read_Buffer_Size_Command,
    HCI_LE_Read_Local_Supported_Features_Command,
    HCI_LE_Set_Event_Mask_Command,
    HCI_LE_Set_Random_Address_Command,
    HCI_LE_Set_Scan_Enable,
    HCI_LE_Set_Scan_Parameters_Command,
    HCI_Number_Of_Completed_Packets_Event,
    HCI_Read_BD_ADDR_Command,
    HCI_Read_Buffer_Size_Command,
    HCI_Read_Local_Supported_Commands_Command,
    HCI_Read_Local_Supported_Features_Command,
    HCI_Read_Local_Version_Command,
    HCI_Reset,
    HCI_Set_Event_Mask_Command,
    HCI_Write_LE_Host_Supported_Command,
    HCI_Write_Scan_Enable_Command,
    HCI_Write_Simple_Pairing_Mode_Command,
    PacketRegistry,
    decode_hci_packet,
)

__all__ = [
    # Constants
    "OGF",
    "EventCode",
    "ErrorCode",
    "LEMetaSubEvent",
    "make_opcode",
    "ogf_ocf",
    "HCI_COMMAND_PACKET",
    "HCI_ACL_PACKET",
    "HCI_SCO_PACKET",
    "HCI_EVENT_PACKET",
    "HCI_ISO_PACKET",
    "HCI_RESET",
    "HCI_READ_BD_ADDR",
    "HCI_READ_BUFFER_SIZE",
    "HCI_READ_LOCAL_VERSION",
    "HCI_LE_READ_BUFFER_SIZE",
    "HCI_LE_SET_SCAN_ENABLE",
    "HCI_DISCONNECT",
    "HCI_SET_EVENT_MASK",
    "HCI_LE_SET_EVENT_MASK",
    "HCI_WRITE_LE_HOST_SUPPORTED",
    "HCI_WRITE_SIMPLE_PAIRING_MODE",
    "HCI_WRITE_SCAN_ENABLE",
    "HCI_HOST_BUFFER_SIZE",
    "HCI_LE_SET_SCAN_PARAMS",
    "HCI_LE_SET_RANDOM_ADDRESS",
    "HCI_READ_LOCAL_SUPPORTED_COMMANDS",
    "HCI_READ_LOCAL_SUPPORTED_FEATURES",
    "HCI_LE_READ_LOCAL_SUPPORTED_FEATURES",
    # Packets
    "HCIPacket",
    "HCICommand",
    "HCIEvent",
    "HCIACLData",
    "HCISCOData",
    "HCIISOData",
    "HCI_Reset",
    "HCI_LE_Set_Scan_Enable",
    "HCI_Read_BD_ADDR_Command",
    "HCI_Read_Local_Version_Command",
    "HCI_Read_Buffer_Size_Command",
    "HCI_LE_Read_Buffer_Size_Command",
    "HCI_Read_Local_Supported_Commands_Command",
    "HCI_Read_Local_Supported_Features_Command",
    "HCI_LE_Read_Local_Supported_Features_Command",
    "HCI_Set_Event_Mask_Command",
    "HCI_LE_Set_Event_Mask_Command",
    "HCI_Write_LE_Host_Supported_Command",
    "HCI_Write_Simple_Pairing_Mode_Command",
    "HCI_Write_Scan_Enable_Command",
    "HCI_Host_Buffer_Size_Command",
    "HCI_LE_Set_Scan_Parameters_Command",
    "HCI_LE_Set_Random_Address_Command",
    "HCI_Command_Complete_Event",
    "HCI_Command_Status_Event",
    "HCI_Connection_Complete_Event",
    "HCI_Disconnection_Complete_Event",
    "HCI_Number_Of_Completed_Packets_Event",
    "HCI_LE_Meta_Event",
    "PacketRegistry",
    "decode_hci_packet",
    # Flow control
    "CommandFlowController",
    "ACLFlowController",
    # Controller
    "HCIConnection",
    "ConnectionManager",
    "HCIController",
    # Virtual
    "VirtualController",
]
