"""'tools rpa' — IRK and Resolvable Private Address utilities."""
from __future__ import annotations

import argparse
import os
import sys

from pybluehost.ble.smp import SMPCrypto


def register_rpa_commands(subparsers: argparse._SubParsersAction) -> None:
    rpa_parser = subparsers.add_parser("rpa", help="IRK / RPA utilities")
    rpa_subs = rpa_parser.add_subparsers(dest="rpa_cmd")

    p_irk = rpa_subs.add_parser("gen-irk", help="Generate a random 16-byte IRK")
    p_irk.set_defaults(func=_cmd_gen_irk)

    p_rpa = rpa_subs.add_parser("gen-rpa", help="Generate an RPA from an IRK")
    p_rpa.add_argument("--irk", required=True, help="IRK as 32 hex chars")
    p_rpa.set_defaults(func=_cmd_gen_rpa)

    p_ver = rpa_subs.add_parser("verify", help="Verify an RPA was generated by an IRK")
    p_ver.add_argument("--irk", required=True, help="IRK as 32 hex chars")
    p_ver.add_argument("--addr", required=True, help="BD_ADDR as XX:XX:XX:XX:XX:XX")
    p_ver.set_defaults(func=_cmd_verify)


def _parse_irk(s: str) -> bytes:
    irk = bytes.fromhex(s)
    if len(irk) != 16:
        raise ValueError(f"IRK must be 16 bytes (32 hex chars), got {len(irk)}")
    return irk


def _format_addr(addr_bytes: bytes) -> str:
    """addr_bytes: 6 bytes, MSB-first → XX:XX:XX:XX:XX:XX"""
    return ":".join(f"{b:02X}" for b in addr_bytes)


def _cmd_gen_irk(args: argparse.Namespace) -> int:
    print(os.urandom(16).hex())
    return 0


def _cmd_gen_rpa(args: argparse.Namespace) -> int:
    try:
        irk = _parse_irk(args.irk)
    except ValueError as e:
        print(f"Error: {e}", file=sys.stderr)
        return 1
    # prand: 24 bits, with top two bits = 0b01 (resolvable type)
    prand_int = int.from_bytes(os.urandom(3), "big")
    prand_int = (prand_int & 0x3FFFFF) | 0x400000  # top 2 bits = 01
    prand = prand_int.to_bytes(3, "big")
    hash_bytes = SMPCrypto.ah(irk, prand)
    addr_bytes = prand + hash_bytes  # 6 bytes total, MSB → LSB
    print(f"IRK:    {irk.hex()}")
    print(f"prand:  {prand.hex()}")
    print(f"hash:   {hash_bytes.hex()}")
    print(f"RPA:    {_format_addr(addr_bytes)}/random")
    return 0


def _cmd_verify(args: argparse.Namespace) -> int:
    try:
        irk = _parse_irk(args.irk)
    except ValueError as e:
        print(f"Error: {e}", file=sys.stderr)
        return 1
    addr_str = args.addr.strip()
    parts = addr_str.split(":")
    if len(parts) != 6:
        print(f"Error: invalid BD_ADDR: {addr_str!r}", file=sys.stderr)
        return 1
    try:
        addr_bytes = bytes(int(p, 16) for p in parts)  # MSB → LSB
    except ValueError:
        print(f"Error: invalid BD_ADDR: {addr_str!r}", file=sys.stderr)
        return 1
    prand = addr_bytes[0:3]
    hash_observed = addr_bytes[3:6]
    hash_expected = SMPCrypto.ah(irk, prand)
    if hash_observed == hash_expected:
        print("match")
        return 0
    print("no match")
    return 1
